INLOOP	TD	INDEV	.TEST INPUT DEICE
	JEQ	INLOOP	.LOOP UNTIL DEVICE IS READY
	RD	INDEV	.READ ONE BYTE FROM INPUT DEVICE
	STCH	DATA	.STORE BYTE THAT WAS READ
		
OUTLP	TD	OUTDEV	.TEST OUTPUT DEVICE
	JEQ	OUTLP	.LOOP UNTILL DEVUCE IS READY
	LDCH	DATA	.LOAD DATA BYTE INTO REGISTER A
	WD	OUTDEV	.WRITE ONE BYTE TO OUTPUT DEVICE
		
INDEV	BYTE	0	.INPUT DEVICE NUMBER
OUTDEV	BYTE	1	.OUTPUT DEVICE NUMBER
DATA	RESB	1	.ONE-BYTE VARIABLE