.Original problem link
./https://www.acmicpc.net/problem/10773
MAIN	START	0
FIRST	STL	RETADR		.SAVE RETURN ADDRESS
	JSUB	STINIT
INLOOP	TD	INDEV		.TEST INPUT DEVICE
	JEQ	INLOOP		.LOOP UNTIL DEVICE IS READY
	RD	INDEV		.READ ONE BYTE FROM INPUT(THE INPUT NUMBER)
	SUB	#48		.MUST  48(ASCII CODE)
	STA	LENGTH		.STORE BYTE THAT WAS READ
	RD	INDEV
	
FLOOP	RD	INDEV
	SUB	#48
	COMP	ZERO		.WAS IT IS ZERO?
	JEQ	POP		.IF IT IS ZERO, POP IT
	JGT	PUSH		.IF IT IS NOT ZERO, PUSH IT
ABC	RD	INDEV
	TIX	LENGTH		.FOR LOOP - INPUT UNTIL LENGTH
	JLT	FLOOP
	LDX	ZERO

	
SLOOP	LDA	@TMP
	ADD	SUM
	STA	SUM
	LDA	TMP
	ADD	#3
	STA	TMP
	TIX	CNT
	JLT	SLOOP
	JEQ	PRINT


PRINT	TD	OUTDEV
	JEQ	PRINT
	LDA	SUM
	DIV	ASEN
	ADD	#48
	WD	OUTDEV
	LDA	SUM
	DIV	ASEN
	MUL	ASEN
	STA	LEFT
	LDA	SUM
	SUB	LEFT
	ADD	#48
	WD	OUTDEV	
	END	MAIN
	
STINIT	LDA	#STACK		.STACK INIT
	STA	STKPTR
	STA	TMP
	RSUB

PUSH	STA	@STKPTR
	LDA	STKPTR
	ADD	#3
	STA	STKPTR
	LDA	CNT
	ADD	#1
	STA	CNT
	J	ABC

POP	LDA	STKPTR
	SUB	#3
	STA	STKPTR
	LDA	ZERO
	STA	@STKPTR
	LDA	CNT
	SUB	#1
	STA	CNT
	J	ABC
	
ZERO	WORD	0
END	WORD	1
ASEN	WORD	10
LEFT	RESW	1
RETADR	RESW	1
LENGTH	RESW	1
INDEV	BYTE	0
OUTDEV	BYTE	1
INPUT	WORD	0
MAXLEN	WORD	4096
STKPTR	RESW	1
TMP	RESW	1
STACK	RESW	10
SUM	RESW	1
CNT	RESW	1